{{- if eq .Values.mode "devnet" }}

{{- if gt (.Values.nodeCount | int) 10 }}
{{- fail "nodeCount cannot be greater than 10" }}
{{- end }}

{{- $basePort := .Values.besu.baseNodePort }}
{{- $prefix := .Values.besu.nodeNamePrefix }}

{{- range $i, $ := until (.Values.nodeCount | int) }}
{{- $name := printf "%s%d" $prefix (add $i 1) }}
apiVersion: core.paladin.io/v1alpha1
kind: Besu
metadata:
  name: {{ .Values.network }}-{{ $name }}
  labels:
    app.kubernetes.io/name: {{ .Values.network }}-{{ $name }}
    paladin.io/network: {{ .Values.network }}
spec:
  genesis: testnet
  service:
    type: NodePort
    ports:
      - name: rpc-http
        port: 8545
        nodePort: {{ add $basePort (mul $i 100) }}
      - name: rpc-ws
        port: 8546
        nodePort: {{ add $basePort (add (mul $i 100) 1) }}
      - name: graphql-http
        port: 8547
        nodePort: {{ add $basePort (add (mul $i 100) 2) }}
---
{{- end }}
{{- end }}