// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: Paladin.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Metastate is spent, unspent, pending or spending
type GetStatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MetaState string `protobuf:"bytes,1,opt,name=MetaState,proto3" json:"MetaState,omitempty"`
}

func (x *GetStatesRequest) Reset() {
	*x = GetStatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Paladin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatesRequest) ProtoMessage() {}

func (x *GetStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Paladin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatesRequest.ProtoReflect.Descriptor instead.
func (*GetStatesRequest) Descriptor() ([]byte, []int) {
	return file_Paladin_proto_rawDescGZIP(), []int{0}
}

func (x *GetStatesRequest) GetMetaState() string {
	if x != nil {
		return x.MetaState
	}
	return ""
}

type GetStatesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateId []string `protobuf:"bytes,1,rep,name=stateId,proto3" json:"stateId,omitempty"`
}

func (x *GetStatesReply) Reset() {
	*x = GetStatesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Paladin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatesReply) ProtoMessage() {}

func (x *GetStatesReply) ProtoReflect() protoreflect.Message {
	mi := &file_Paladin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatesReply.ProtoReflect.Descriptor instead.
func (*GetStatesReply) Descriptor() ([]byte, []int) {
	return file_Paladin_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatesReply) GetStateId() []string {
	if x != nil {
		return x.StateId
	}
	return nil
}

type DomainCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DomainId  string   `protobuf:"bytes,1,opt,name=domainId,proto3" json:"domainId,omitempty"`
	Id        string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Command   string   `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Arguments []string `protobuf:"bytes,4,rep,name=arguments,proto3" json:"arguments,omitempty"`
}

func (x *DomainCommand) Reset() {
	*x = DomainCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Paladin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DomainCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainCommand) ProtoMessage() {}

func (x *DomainCommand) ProtoReflect() protoreflect.Message {
	mi := &file_Paladin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainCommand.ProtoReflect.Descriptor instead.
func (*DomainCommand) Descriptor() ([]byte, []int) {
	return file_Paladin_proto_rawDescGZIP(), []int{2}
}

func (x *DomainCommand) GetDomainId() string {
	if x != nil {
		return x.DomainId
	}
	return ""
}

func (x *DomainCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DomainCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *DomainCommand) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type DomainEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DomainId  string   `protobuf:"bytes,1,opt,name=domainId,proto3" json:"domainId,omitempty"`
	Id        string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CommandId string   `protobuf:"bytes,3,opt,name=commandId,proto3" json:"commandId,omitempty"`
	Arguments []string `protobuf:"bytes,4,rep,name=arguments,proto3" json:"arguments,omitempty"`
}

func (x *DomainEvent) Reset() {
	*x = DomainEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Paladin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DomainEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainEvent) ProtoMessage() {}

func (x *DomainEvent) ProtoReflect() protoreflect.Message {
	mi := &file_Paladin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainEvent.ProtoReflect.Descriptor instead.
func (*DomainEvent) Descriptor() ([]byte, []int) {
	return file_Paladin_proto_rawDescGZIP(), []int{3}
}

func (x *DomainEvent) GetDomainId() string {
	if x != nil {
		return x.DomainId
	}
	return ""
}

func (x *DomainEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DomainEvent) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *DomainEvent) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

var File_Paladin_proto protoreflect.FileDescriptor

var file_Paladin_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x50, 0x61, 0x6c, 0x61, 0x64, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0e, 0x70, 0x61, 0x6c, 0x61, 0x64, 0x69, 0x6e, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x22,
	0x30, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x65, 0x74, 0x61, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x65, 0x74, 0x61, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x22, 0x2a, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x74, 0x65, 0x49, 0x64, 0x22, 0x73, 0x0a,
	0x0d, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x22, 0x75, 0x0a, 0x0b, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61,
	0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09,
	0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x32, 0xb5, 0x01, 0x0a, 0x0e, 0x50, 0x61,
	0x6c, 0x61, 0x64, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x09,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x12, 0x20, 0x2e, 0x70, 0x61, 0x6c, 0x61,
	0x64, 0x69, 0x6e, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x61,
	0x6c, 0x61, 0x64, 0x69, 0x6e, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x52, 0x0a,
	0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12,
	0x1b, 0x2e, 0x70, 0x61, 0x6c, 0x61, 0x64, 0x69, 0x6e, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x1d, 0x2e, 0x70,
	0x61, 0x6c, 0x61, 0x64, 0x69, 0x6e, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x44, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x00, 0x28, 0x01, 0x30,
	0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Paladin_proto_rawDescOnce sync.Once
	file_Paladin_proto_rawDescData = file_Paladin_proto_rawDesc
)

func file_Paladin_proto_rawDescGZIP() []byte {
	file_Paladin_proto_rawDescOnce.Do(func() {
		file_Paladin_proto_rawDescData = protoimpl.X.CompressGZIP(file_Paladin_proto_rawDescData)
	})
	return file_Paladin_proto_rawDescData
}

var file_Paladin_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Paladin_proto_goTypes = []any{
	(*GetStatesRequest)(nil), // 0: paladin.domain.GetStatesRequest
	(*GetStatesReply)(nil),   // 1: paladin.domain.GetStatesReply
	(*DomainCommand)(nil),    // 2: paladin.domain.DomainCommand
	(*DomainEvent)(nil),      // 3: paladin.domain.DomainEvent
}
var file_Paladin_proto_depIdxs = []int32{
	0, // 0: paladin.domain.PaladinService.GetStates:input_type -> paladin.domain.GetStatesRequest
	3, // 1: paladin.domain.PaladinService.RegisterDomain:input_type -> paladin.domain.DomainEvent
	1, // 2: paladin.domain.PaladinService.GetStates:output_type -> paladin.domain.GetStatesReply
	2, // 3: paladin.domain.PaladinService.RegisterDomain:output_type -> paladin.domain.DomainCommand
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Paladin_proto_init() }
func file_Paladin_proto_init() {
	if File_Paladin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Paladin_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetStatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Paladin_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetStatesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Paladin_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*DomainCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Paladin_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*DomainEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Paladin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Paladin_proto_goTypes,
		DependencyIndexes: file_Paladin_proto_depIdxs,
		MessageInfos:      file_Paladin_proto_msgTypes,
	}.Build()
	File_Paladin_proto = out.File
	file_Paladin_proto_rawDesc = nil
	file_Paladin_proto_goTypes = nil
	file_Paladin_proto_depIdxs = nil
}
