// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.21.12
// source: Paladin.proto

package domain

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	PaladinService_GetStates_FullMethodName      = "/paladin.domain.PaladinService/GetStates"
	PaladinService_RegisterDomain_FullMethodName = "/paladin.domain.PaladinService/RegisterDomain"
)

// PaladinServiceClient is the client API for PaladinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type PaladinServiceClient interface {
	// Fetches states in a given meta state
	GetStates(ctx context.Context, in *GetStatesRequest, opts ...grpc.CallOption) (*GetStatesReply, error)
	// Domain opening a bidirectional stream to receive commands and send events
	RegisterDomain(ctx context.Context, opts ...grpc.CallOption) (PaladinService_RegisterDomainClient, error)
}

type paladinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaladinServiceClient(cc grpc.ClientConnInterface) PaladinServiceClient {
	return &paladinServiceClient{cc}
}

func (c *paladinServiceClient) GetStates(ctx context.Context, in *GetStatesRequest, opts ...grpc.CallOption) (*GetStatesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatesReply)
	err := c.cc.Invoke(ctx, PaladinService_GetStates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paladinServiceClient) RegisterDomain(ctx context.Context, opts ...grpc.CallOption) (PaladinService_RegisterDomainClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PaladinService_ServiceDesc.Streams[0], PaladinService_RegisterDomain_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &paladinServiceRegisterDomainClient{ClientStream: stream}
	return x, nil
}

type PaladinService_RegisterDomainClient interface {
	Send(*DomainEvent) error
	Recv() (*DomainCommand, error)
	grpc.ClientStream
}

type paladinServiceRegisterDomainClient struct {
	grpc.ClientStream
}

func (x *paladinServiceRegisterDomainClient) Send(m *DomainEvent) error {
	return x.ClientStream.SendMsg(m)
}

func (x *paladinServiceRegisterDomainClient) Recv() (*DomainCommand, error) {
	m := new(DomainCommand)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PaladinServiceServer is the server API for PaladinService service.
// All implementations must embed UnimplementedPaladinServiceServer
// for forward compatibility
//
// The greeting service definition.
type PaladinServiceServer interface {
	// Fetches states in a given meta state
	GetStates(context.Context, *GetStatesRequest) (*GetStatesReply, error)
	// Domain opening a bidirectional stream to receive commands and send events
	RegisterDomain(PaladinService_RegisterDomainServer) error
	mustEmbedUnimplementedPaladinServiceServer()
}

// UnimplementedPaladinServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPaladinServiceServer struct {
}

func (UnimplementedPaladinServiceServer) GetStates(context.Context, *GetStatesRequest) (*GetStatesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStates not implemented")
}
func (UnimplementedPaladinServiceServer) RegisterDomain(PaladinService_RegisterDomainServer) error {
	return status.Errorf(codes.Unimplemented, "method RegisterDomain not implemented")
}
func (UnimplementedPaladinServiceServer) mustEmbedUnimplementedPaladinServiceServer() {}

// UnsafePaladinServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaladinServiceServer will
// result in compilation errors.
type UnsafePaladinServiceServer interface {
	mustEmbedUnimplementedPaladinServiceServer()
}

func RegisterPaladinServiceServer(s grpc.ServiceRegistrar, srv PaladinServiceServer) {
	s.RegisterService(&PaladinService_ServiceDesc, srv)
}

func _PaladinService_GetStates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaladinServiceServer).GetStates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaladinService_GetStates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaladinServiceServer).GetStates(ctx, req.(*GetStatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaladinService_RegisterDomain_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PaladinServiceServer).RegisterDomain(&paladinServiceRegisterDomainServer{ServerStream: stream})
}

type PaladinService_RegisterDomainServer interface {
	Send(*DomainCommand) error
	Recv() (*DomainEvent, error)
	grpc.ServerStream
}

type paladinServiceRegisterDomainServer struct {
	grpc.ServerStream
}

func (x *paladinServiceRegisterDomainServer) Send(m *DomainCommand) error {
	return x.ServerStream.SendMsg(m)
}

func (x *paladinServiceRegisterDomainServer) Recv() (*DomainEvent, error) {
	m := new(DomainEvent)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PaladinService_ServiceDesc is the grpc.ServiceDesc for PaladinService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaladinService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paladin.domain.PaladinService",
	HandlerType: (*PaladinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStates",
			Handler:    _PaladinService_GetStates_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterDomain",
			Handler:       _PaladinService_RegisterDomain_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "Paladin.proto",
}
